### ISSUE TITLE
Not working on my Flarum

### ISSUE THREAD

**Issue by tolgaaaltas** [892768447/flarum-ext-bing-wallpaper#1]
I'm not sure it's working well. I've tried on my Flarum with/without FoF Night Mode but wallpaper doesn't exist.

**Comment by 892768447** [comment]
1. visit your url https://xxx.xxx/api/irony/bing/wallpaper
can you see bing wallpaper?
for example my site: https://pyqt.site/api/irony/bing/wallpaper

2. use browser dev tool (F12) to check the `body` and `id="app"` style

```css
body {
  background-attachment: fixed;
  background-image: url(/api/irony/bing/wallpaper);
}

#app {
  background-color: rgba(255, 255, 255, .8);
}

.Scrubber-handle {
  background: none;
}
```
